########################### NETWORKS
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.48.0/24"
          gateway: "192.168.48.1"
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim

include:
  ########################### SERVICES

  #CORE
  - compose/socket-proxy.yml
  - compose/portainer.yml
  
  #MEDIA
  - compose/plex.yml

  # DOWNLOADERS
  - compose/sabnzbd.yml

  # PVRS
  - compose/radarr.yml
  - compose/sonarr.yml
  - compose/prowlarr.yml

  # COMPLEMENTARY APPS
  - compose/bazarr.yml
  - compose/overseer.yml

  # UTILITIES
  - compose/homeassistant.yml

  # WEBSERVER
  - compose/caddy.yml
 
  # METRICS
  - compose/grafana.yml
  - compose/prometheus.yml
