services:
  # Sonarr - TV Shows Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    networks:
      - default
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonar:/config
      - $DATADIR/media/shows:/data/shows
      - $DOWNLOADSDIR:/data/downloads 
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID