services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    networks:
      default:
        ipv4_address: 192.168.48.10
    ports:
      - "6767:6767"
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $DATADIR/data:/data
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
