services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  
    volumes:
      - $DOCKERDIR/appdata/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/caddy/data:/data
      - $DOCKERDIR/appdata/caddy/config:/config
      - $DOCKERDIR/appdata/caddy/html:/data/html
      - $DOCKERDIR/certs:/etc/ssl:ro
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/caddy"
