services:
  # Firefox - Web Browser (SSL and Dark Mode enabled)
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined 
    restart: unless-stopped
    networks:
      - default
    ports:
      - "5800:5800"
    volumes:
      - $DOCKERDIR/appdata/firefox:/config
      - $DOWNLOADSDIR:/data/downloads
      - /dev/shm:/dev/shm
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      SECURE_CONNECTION: 1
      DARK_MODE: 1
