services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.70
    ports:
      - "3000:3000"
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_PW
      - TZ=${TZ}
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/firefox"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - prometheus