services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.70
    ports:
      - "3000:3000"
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=${TZ}
