services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - $DOCKERDIR/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - default
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/homeassistant"
      - "com.centurylinklabs.watchtower.enable=true"