services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tokyo
      # - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseer/config:/app/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.20
