services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/overseer/config:/app/config
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.20
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/overseer"
      - "com.centurylinklabs.watchtower.enable=true"
