services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest 
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
      - "9000:9000"
    volumes:
      - $DOCKERDIR/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      - TZ=$TZ
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/portainer"
      - "com.centurylinklabs.watchtower.enable=true"

