services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.71
    ports:
      - "9090:9090"
    volumes:
      - $DOCKERDIR/appdata/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
