services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.48.30
    ports:
      - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/prowlarr"
