services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    security_opt:
      - no-new-privileges:true
    restart: "no"
    networks:
      default:
        ipv4_address: 192.168.48.60
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonar:/config
      - $DATADIR/media/shows:/data/shows
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK: 002