services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/uptime-kuma:/app/data
    labels:
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/uptime-kuma"
      - "com.centurylinklabs.watchtower.enable=true"