services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=$TZ
    command: --cleanup --label-enable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "org.label-schema.version=${VERSION}"
      - "org.label-schema.build-date=${BUILD_DATE}"
      - "org.label-schema.vcs-ref=${VCS_REF}"
      - "org.label-schema.vcs-url=https://github.com/fdool73/arrstack/compose/watchtower"
      


